### ISSUE TITLE
[!] Network error : socket hang up

### ISSUE THREAD

**Issue by jgudan** [seraum/nectarjs#1]
Trying to make some tests with nectar (master branch) and all I get in any combination is "[!] Network error : socket hang up"after waiting for a minute or so.
Any help?

**Comment by adrien-thierry** [comment]
What are your OS and NodeJS version ? 

Furthermore, tests are currently closed, we focus on our KickStarter campaign before to reopen in alpha : kickstarter.com/projects/adrien-thierry/nectarjs-compile-javascript-for-and-from-any-devic

**Comment by jgudan** [comment]
MacOS 10.11.6, Node.js v7.7.1
Will tests be reopened? I would really like to Nectar work.

**Comment by adrien-thierry** [comment]
Yes, pre-alpha will reopen soon

have you read the KS campaign ?

**Comment by adrien-thierry** [comment]
You can test NectarJS right now : http://nectarjs.com/key/

**Comment by davidfrogley** [comment]
I have signed up to test NectarJS and gotten my ID and key. However, my test app still has this same error. Does it have something to do with using socket.io?

**Comment by adrien-thierry** [comment]
Hi David,

are you behind a proxy ?

**Comment by davidfrogley** [comment]
I was not when I was trying to run the example. I can run the example without problems using just node.

**Comment by adrien-thierry** [comment]
Maybe you are in a directory with a lot of file, test it in a new folder
