### ISSUE TITLE
Why does javascript similar to my code exist in memory?

### ISSUE THREAD

**Issue by NoCheroot** [seraum/nectarjs#10]
Compiled this:
```
var x = "xxx";
y = x;
z = y;
console.log(x + y + z);
```
Loaded into windbg and ran the following commands:
```
g
s -a 0 L?80000000/2 "xxx"
```

Saw something interesting at 0068d713, so dumped it.
```
d 0068d713-15 L50
```
![2017-12-26 12_04_50-win 10 dt on lt-01012252 - virtual machine connection](https://user-images.githubusercontent.com/10468415/34362037-8d09653c-ea35-11e7-9ccc-5817241fd049.png)

Why does javascript similar to my code exist in memory?

**Comment by adrien-thierry** [comment]
Hi,
As we wanted to launch fastly a boostraped version, the actual version embed a JS engine for Linux/Windows,

We are finishing a new release of the core compiler and will update it soon,

stay tuned on Slack : http://api.nectarjs.com:3000/ 

More info here : https://medium.com/@adrien.thierryfr/nectarjs-compiling-javascript-into-native-binaries-for-every-platform-2efb2083a4a

**Comment by NoCheroot** [comment]
My mistake.  I though this was meant to compile javascript to machine code, and I wanted to see the optimizations.

**Comment by adrien-thierry** [comment]
No, it's not a mistake, it will compile to machine code

for testing purpose, we have replaced the compiler by an engine, but we will replace soon the engine by compiled machine code

**Comment by NoCheroot** [comment]
I compiled your fibonacci algorithm example:

```
function fibonacci(n)
{
if (n < 2)  return n;
return fibonacci(n - 2) + fibonacci(n - 1);
}
console.log(fibonacci(30));
```

It looks like this in memory:
![2017-12-28 12_19_22-win 10 dt on lt-01012252 - virtual machine connection](https://user-images.githubusercontent.com/10468415/34419642-9a2ca170-ebca-11e7-8a43-72f6e6749bd6.png)

The important bit is:

```
function t(n){return n<2?n:t(n-2)+t(n-1)}console.log(t(30))}
```

This looks like uglifyjs output.  The rest looks like garbage code.  When I run the fibonacci example code through an obfuscator, I get this:

```
!function(a,b){function c(b,d){var e,f;if("."!=b[0]&&"/"!=b[0])return a(b);if(d=d||"root",e=c.resolve(b),!e&&/\.json$/i.test(b))return a("./"+c.basename(b));if(f=c.cache[e],!f)try{return a(b)}catch(g){throw Error('failed to require "'+b+'"
from '+d+"\n"+g.message+"\n"+g.stack)}return f.exports||(f.exports={},f.call(f.exports,f,f.exports,c.relative(e))),f.exports}c.cache={},c.basename=a("path").basename,c.resolve=function(b){var d,e,f,g;if("."!=b[0])return a.resolve(b);for(d="
/"===b.slice(-1)?b:b+"/",e=[b,b+".js",d+"index.js",b+".json",d+"index.json"],f=0;g=e[f];f++)if(c.cache[g])return g},c.register=function(a,b){c.cache[a]=b},c.relative=function(a){function b(b){var d,e,f,g,h;if("."!=b[0])return c(b);for(d=a.s
plit("/"),e=b.split("/"),d.pop(),f=0,g=e.length;g>f;f+=1)h=e[f],".."==h?d.pop():"."!=h&&d.push(h);return c(d.join("/"),a)}return b.resolve=c.resolve,b.cache=c.cache,b},c.register("./orig.js",function(){function d(a){return 2>a?a:d(a-2)+d(a-
1)}console.log(d(30))}),b.exports=c("./orig.js")}(require,module);
```

Similar to what I'm seeing in memory, but some differences in approach.  Maybe I'm using a different obfuscator, or different options.

I only have time to look at this on my lunch break, so unfortunately I won't have an opportunity any time soon to answer these on my own.

* Is any portion of your compiler involved in creating the output executables at this stage at all?  Or, are the executables just our code, an embedded runtime, and layers of obfuscation?
* Which engine, as you put it, are you embedding?  Is it your own?  Part of the compiler?
* Can we have access to files produced by the version of the core compiler you are working on now so we can start to get an idea of its nature?

**Comment by NoCheroot** [comment]
Answered a couple of my questions myself.

```
console.log(Duktape.version)
```

Outputs 20299.

Maybe I missed it (I didn't look very hard), but I have not seen Duktape (https://github.com/svaarala/duktape) in your documentation or articles.  Until Duktape is replaced by your compiler, this seems like important information to have for anyone trying to understand behavior of their code, or even assess NectarJS as an option for projects.

**Comment by adrien-thierry** [comment]
Yes,

we have uptaded NectarJS with the core compiler today, no more Duktape or JS engines, doc's coming soon

**Comment by NoCheroot** [comment]
Just tried it.  Executable still contains obfuscated javascript and Duktape.
