### ISSUE TITLE
win-x86-64 target executables still use Duktape

### ISSUE THREAD

**Issue by NoCheroot** [seraum/nectarjs#11]
Issue https://github.com/seraum/nectarjs/issues/10 was closed with: 

![image](https://user-images.githubusercontent.com/10468415/34456710-2d9e2bce-ed63-11e7-865e-d5476806941f.png)

However, win-x86-64 target executables compiled since then still appear to use Duktape.

When I compile this:

```
console.log(Duktape.version)
```

It still outputs 20299.

.rdata section still contains strings related to duktape.

![image](https://user-images.githubusercontent.com/10468415/34456667-1d54898a-ed62-11e7-8a5b-c76ec23e7bf8.png)

Has something gone wrong with the update?

**Comment by adrien-thierry** [comment]
Yes, thanks, it's fixed

(update was effective for Linux-* and Windows x86-32)

**Comment by NoCheroot** [comment]
Working as expected now.  Thank you.
